### PR TITLE
Add random task button to load task from web

### PR DESCRIPTION
**Pull request by ageron**
This PR makes it easier for people to get started quickly with the tasks without having to load a new task all the time. Plus, it makes it easier to host this UI on a website so people don't have to download all the JSON tasks locally. I could have done a "next task" and "previous task" button, but when playing around with it I found that I liked having a random challenge.

### CODE REVIEW

**Comment by fchollet** [comment]
Thank you for the PR!

I would recommend keeping the modal and adding a "Pick task at random" button to the modal.

**Comment by ageron** [comment]
Good point, I'll see if I can give that a shot soon.

**Comment by ageron** [comment]
Done, modal is back, with an extra 'Random task' button. This app is fun to play with! 👍 

After playing with it for a while, it feels like I usually follow roughly these steps:
1) **Find salient "landmarks" in each grid**: objects, intersections, patterns. There's no effort in this step: most of the time, these landmarks just seem obvious (i.e., handled by the visual cortex, the process is not accessible via consciousness). In particular, repeated patterns are very easy to spot, and usually they are important.
2) **Find relationships between these landmarks**, within each grid, and across grids (e.g., "every rectangle has a line next to it", or "all output grids are 3x3 with 3 colors). This is also mostly automatic, but some relationships require a bit of search. For example, if all horizontal rectangles are yellow while all vertical rectangles are blue, this just jumps straight at you (=visual cortex magic). But if each rectangle is composed of random colors and only the ones containing a yellow dot are vertical, it might take some time to notice that. In this case the pattern search process is conscious and requires some effort (it's system 2, not system 1): I look for rotations, repetitions, counts, distances, translations, symmetries... It's not an infinite list. Note that I only start searching after I've done a first quick pass through all steps in this list trying to find an obvious pattern.
3) **Describe the output grids' structure as concisely as possible, if necessary using attributes from the input grid's descriptions** (this is the most "magical" step: it's hard to tell how I do this). E.g., "the outputs are always 3x3 grids with 3 columns of different colors. The left color corresponds to the rectangle's color in the input grid., etc.". There's usually only one solution, but in some cases there are two or more: the simplest wins (=the shortest description).
4) **Check that the rule works on all demo pairs**.
5) **Apply the rule to the test input to produce the test output**.

**Comment by fchollet** [comment]
I agree with your introspective analysis. The rough steps are, 1) parse the grids into objects, 2) generate the space of all possible relationships among these objects, 3) reduce that space to the relationships that match the data, 4) apply the resulting program to the input grid. 1) and 2) can be encoded in program form via a kind of ARC DSL.

What's most interesting to me is that we're able to effortlessly identify these relationships without trying them all exhaustively (seemingly), whereas the space of possible relationships is very large. The same could be said about object parsing.

**Comment by ageron** [comment]
Thanks for merging!

**Pull request merged**
